version: "3.8"

services:

  feature-info-agent:
    image: docker.cmclinnovations.com/feature-info-agent:1.0.0-SNAPSHOT
    container_name: feature-info-agent
    build:
      context: "../"
      dockerfile: "./docker/Dockerfile"
    restart: unless-stopped
    hostname: feature-info-agent
    environment:
      LOG4J_FORMAT_MSG_NO_LOOKUPS: "true"
      PROPERTIES_FILE: "/root/feature-info.properties"
    ports:
      - "55050:8080" 