name: Docker Image CI

on:
  push:
    branches:
      - main
    paths:
      - code/**
  workflow_dispatch:

jobs:
  build-and-push-image:
    runs-on: ubuntu-latest

    permissions:
      packages: write

    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set version variables from file
        id: read-version
        run: |
          VERSION=$(cat VERSION)
          echo "VERSION=$VERSION" >> $GITHUB_ENV
          echo "MAJOR=$(echo $VERSION | cut -d. -f1)" >> $GITHUB_ENV
          echo "MINOR=$(echo $VERSION | cut -d. -f1).$(echo $VERSION | cut -d. -f2)" >> $GITHUB_ENV

      # Set up Maven settings with GitHub token (currently needs one with access to packages on the old org. Will be replaced with the regular token when everything in same org)
      - name: Set up Maven settings
        run: |
          mkdir -p ~/.m2
          echo "<settings><servers><server><id>github</id><username>${{ secrets.USHCODE_USERNAME }}</username><password>${{ secrets.USHCODE_PACKAGE_TOKEN }}</password></server></servers></settings>" > ~/.m2/settings.xml

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build docker image and push to ghcr
        uses: docker/build-push-action@v6
        with:
          push: true
          tags: |
            ghcr.io/theworldavatar/feature-info-agent:latest
            ghcr.io/theworldavatar/feature-info-agent:${{ env.VERSION }}
            ghcr.io/theworldavatar/feature-info-agent:${{ env.MAJOR }}
            ghcr.io/theworldavatar/feature-info-agent:${{ env.MINOR }}
